### ISSUE TITLE
既にプレイリストに登録したトラックがRecommendに表示される。

### ISSUE THREAD

**Issue by ghost** [yuki-oshima-revenant/spotify-mix-automation#1]
Qiitaで記事を読みまして、早速楽しく利用させて頂いてます😄
一点だけ、こうなると良いなという点があったので上げさせて頂きます。
最後に登録した曲を元にAPIリクエストしている以上、取得されるレコメンド楽曲が重複するのは仕方ないかもしれません。
[Web API Reference > Get Recommendations](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-recommendations)の項目で楽曲を除外するパラメーターは見当たらなかったので
もし除外するのであれば、クライアント側で制御する必要があるかもしれません。
完成品でしたらお節介で申しわけありません:bow: そのままクローズしていただいて大丈夫です。
![FireShot Capture 056 - AUTOMISCE - automisce unronritaro net](https://user-images.githubusercontent.com/52518769/109272461-3c593f80-7854-11eb-94d9-03df21c78e91.png)

**Comment by yuki-oshima-revenant** [comment]
@takapon-dev ご利用&ご要望ありがとうございます！それほど難しくなさそうなので、時間見つけて改修しておきますね。

**Comment by yuki-oshima-revenant** [comment]
@takapon-dev 
e621940d36f39c6b60c41649774d1eac8408d809
こちらのコミットで修正して反映しておきました。ご要望ありがとうございました！

**Comment by ottonove** [comment]
@yuki-oshima-revenant 
初めまして。ottonoveと申します。
ようやく1年が経過したばかりの、ひよっこプログラマです。

昨日こちらのプロジェクトを知り、とても興味を惹かれました！
そしてちょうどissueが挙がっていたため、人生初のOSSへのプルリクしてみようと思ったのですが、一歩遅く、すでに対応されていましたね^^;

私もこんな感じで考えましたので、お伝えだけしておきます。
```
// pages/index.tsx

{recommendData && recommendData.upperTracks.map((track) => {

  if (playlistContent.find((playlistTrack) => (playlistTrack.id === track.id))) {
      console.log("upperTracks 重複あり:", track.name);
      return;
  }
  ...略...
})}

// downerTracksにも同様の処理を追加
```

フィルターを作る事も考えたのですが、この様に作れば良いのですね。
勉強になりました！
